title: Meu Portfólio
description: Bem-vindo ao meu portfólio!
baseurl: "" # Mantenha vazio se estiver hospedando no root
url: "https://SEU_USUARIO.github.io/portfolio"
theme: minima
author: 
  name: Seu Nome
  email: seuemail@email.com
  github: https://github.com/SEU_USUARIO
markdown: kramdown
permalink: pretty