title: Nathan Dezan
description: Bem-vindo ao meu portfólio!
baseurl: ""
url: "https://nathandezan.github.io/"
theme: minima
author: 
  name: Nathan Dezan
  email: dezannathan@email.com
  github: https://github.com/NathanDezan
markdown: kramdown
permalink: pretty
minima:
  skin: dark
header_pages:
  - index.md
  - projects.md
  - about.md